### ISSUE TITLE
Prefix feature

### ISSUE THREAD

**Issue by mtskf** [alpceylan/flutter-countup#10]
Could we add a prefix to the number?
Eg, I'd like to add "$" in front of the number!

**Comment by mtskf** [comment]
I've found it's already implemented although it's not mentioned in the reademe!
Thanks😊

**Comment by mtskf** [comment]
I've found it's already implemented although it's not mentioned in the reademe!
Thanks😊

**Comment by alpceylan** [comment]
Sorry for the delay but it was already mentioned in the README.
