### ISSUE TITLE
Null-Safety migration

### ISSUE THREAD

**Issue by deimantasa** [alpceylan/flutter-countup#5]
Hey devs,

Is there any ETA for null-safety migration? Do you need help with it? Or this package is not maintained anymore?

Cheers

**Comment by alpceylan** [comment]
I'm not able to code for a while. I will migrate it as soon as possible when I'm able to do so.

**Comment by deimantasa** [comment]
> I'm not able to code for a while. I will migrate it as soon as possible when I'm able to do so.

No probs. It seems it was pretty easy. Give it a look https://github.com/alpceylan/flutter-countup/pull/6

**Comment by alpceylan** [comment]
Thanks a lot! I will merge it now.

**Comment by alpceylan** [comment]
But unfortunately I can only publish it in pub.dev later, sorry :( I'm reopening the issue.

**Comment by deimantasa** [comment]
> But unfortunately I can only publish it in pub.dev later, sorry :( I'm reopening the issue.

No probs. 
For anyone, that desperately need `null-safety`, you can build package from git directly, since `null-safety` was just merged to `master`.

Go into your `pubspec.yaml` and replace
 `countup: <version>`
 with 
```
  countup:
    git: https://github.com/alpceylan/flutter-countup.git
```

**Comment by ChangJoo-Park** [comment]
Please publish it on pub.dev 👍

**Comment by kjawadDeveloper1** [comment]
Yes, publish it.

**Comment by brightmind-loredo** [comment]
Is there any update on publishing the null safe version?

**Comment by alpceylan** [comment]
Sorry for the long delay. I just published the new version on pub.dev
